In [28]:
print('Hallo world')

Hallo world

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('../data/data_sport.csv').head(20)
df

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.5
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    106       128     345.3
13        60    104       132     379.3
14        60     98       123     275.0
15        60     98       120     215.2
16        60    100       120     300.0
17        45     90       112       NaN
18        60    103       123     323.0
19        45     97       125     243.0

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  20 non-null     int64
 1   Pulse     20 non-null     int64
 2   Maxpulse  20 non-null     int64
 3   Calories  19 non-null     float64
dtypes: float64(1), int64(3)
memory usage: 772.0 bytes

In [51]:
df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }
)

In [31]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2   Bonnell, Miss Elizabeth   58  female

In [32]:
df['Age']

0    22
1    35
2    58
Name: Age, dtype: int64

In [33]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2   Bonnell, Miss Elizabeth   58  female

In [45]:
ages = pd.Series([22, 35, 58], name="Age")

In [35]:
ages

0    22
1    35
2    58
Name: Age, dtype: int64

In [37]:
type(ages)

pandas.Series

In [42]:
x = df["Age"].max()

In [43]:
x

np.int64(58)

In [44]:
print(x)

58

In [47]:
y = ages.max()

In [48]:
y

np.int64(58)

In [49]:
print(y)

58

In [52]:
df.describe()

             Age
count   3.000000
mean   38.333333
std    18.230012
min    22.000000
25%    28.500000
50%    35.000000
75%    46.500000
max    58.000000

In [53]:
ages.describe()

count     3.000000
mean     38.333333
std      18.230012
min      22.000000
25%      28.500000
50%      35.000000
75%      46.500000
max      58.000000
Name: Age, dtype: float64

In [8]:
df.describe()

        Duration       Pulse    Maxpulse    Calories
count  20.000000   20.000000   20.000000   19.000000
mean   54.750000  103.900000  131.850000  314.168421
std     8.807144    6.711342   13.918087   73.075753
min    30.000000   90.000000  112.000000  195.100000
25%    45.000000   99.500000  123.000000  261.150000
50%    60.000000  103.000000  129.000000  300.500000
75%    60.000000  109.000000  135.250000  359.650000
max    60.000000  117.000000  175.000000  479.000000